### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by lgx-tech** [event-driven-robotics/hpe-core#104]
Thanks for your work. Could you kindly provide a pretrained model for the evaluation?

**Comment by arrenglover** [comment]
Hi @lgx-tech ,
I think the best pre-trained model is found here:
https://github.com/event-driven-robotics/hpe-core/blob/main/example/movenet/models/h36m_finetuned.pth
but @gaurvigoyal can confirm.

All the best.

**Comment by gaurvigoyal** [comment]
Hey @lgx-tech,

The latest and best pre-trained model is this one: [https://github.com/event-driven-robotics/hpe-core/blob/main/example/movenet/models/e97_valacc0.81209.pth](https://github.com/event-driven-robotics/hpe-core/blob/main/example/movenet/models/e97_valacc0.81209.pth).

All the best!

**Comment by lgx-tech** [comment]
Thank you very much. I will close the issue.
